#spring.application.name=backend
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webapp_db
    username: webappuser
    password: webappuser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: backend

backend:
  app:
    jwtSecret: QW1hc1NlY3VyZUtleUdlbmVyYXRlZF9CaXROV1AxMjM0NTZfSFMtMjU2X0pXVA==
    jwtExpirationMs: 86400000

logging:
  file:
    name: logs/webapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    #com.murat: DEBUG